name: Pull Request

on:
  pull_request:

jobs:
  terraform-plan-and-apply-and-tfmigrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up tfenv
        uses: rhythmictech/actions-setup-tfenv@v0.1.2

      - name: Use tfenv to install required Terraform version
        run: make tfenv

      - name: Install tfmigrate
        run: |
          curl \
            --fail \
            --silent \
            --show-error \
            --location \
            "https://github.com/minamijoyo/tfmigrate/releases/download/v0.3.13/tfmigrate_0.3.13_linux_amd64.tar.gz" \
            --output tfmigrate.tar.gz \

          tar -zxvf tfmigrate.tar.gz
          cp tfmigrate /usr/bin

      - name: Start localstack mock AWS environment
        run: make up

      - name: Bootstrap localstack to have tfmigrate-demo S3 bucket
        run: make bootstrap

      - name: Apply project-one
        run: make project-one

      - name: Apply project-one
        run: make project-two

      - name: Plan tfmigrate migration
        run: make plan-migration

      - name: Apply tfmigrate migration
        run: make apply-migration
